# ----------------------------------------------------------------------------------------------------------------------
# Site customization
# ----------------------------------------------------------------------------------------------------------------------
# Any variable here is referenced in layouts/pages as {{site.XXX}} so something like {{site.googleId}}
# ----------------------------------------------------------------------------------------------------------------------

id: oneops.com
name: OneOps
domain: oneops.com
url: http://oneops.com
description: "OneOps"
twitterId: #
googleId: UA-72734811-2
googlePlus: #
slack_url: https://oneops.slack.com/
slack_channel: oneops

# Parameters for CorpusSearch
searchurl: http://search.oneops.com/search
searchname: 'site-oneops-'
authurl: http://auth.oneops.com/auth
feedbackurl: http://feedback.oneops.com/feedback

navigation:
 - title: Benefits
   url: /benefits.html
 - title: Integrations
   url: /integrations.html
 - title: Contribute
   url: /contribute.html
 - title: About
   url: /about.html
 - title: Documentation
   url: /documentation.html

documentation:
 - title: USERS
   url: /user/overview/
 - title: ADMINS
   url: /admin/overview/
 - title: DEVELOPERS
   url: /developer/overview/

sources:
 confluence:
  server: https://confluence.walmart.com
  pages: [PGPTOOLS/Test]

# ----------------------------------------------------------------------------------------------------------------------
# Theme
# ----------------------------------------------------------------------------------------------------------------------

bootstrapVersion: 3.3.1
#theme: walmart

# ----------------------------------------------------------------------------------------------------------------------
# Jekyll
# ----------------------------------------------------------------------------------------------------------------------
markdown: kramdown
kramddown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

exclude: [jekyll.jar, jekyll.sh, jekyll-stage.sh, jekyll-stage-serve.sh, jekyll-stage-build.sh, linkcheck.sh, linkcheck-results.log]
