# ----------------------------------------------------------------------------------------------------------------------
# Site customization
# ----------------------------------------------------------------------------------------------------------------------
# Any variable here is referenced in layouts/pages as {{site.XXX}} so something like {{site.googleId}}
# ----------------------------------------------------------------------------------------------------------------------

id: oneops.com
name: OneOps
domain: oneops.com
url: http://oneops.com
description: "OneOps"
twitterId: #
googleId: UA-72734811-2
googlePlus: #
slack_url: https://oneops.slack.com/
slack_channel: oneops

# Parameters for CorpusSearch
searchurl: http://search.oneops.com/search
searchname: 'site-oneops-'
authurl: http://auth.oneops.com/auth
feedbackurl: http://feedback.oneops.com/feedback

navigation:
 - title: Benefits
   url: /benefits.html
 - title: Integrations
   url: /integrations.html
 - title: Contribute
   url: /contribute.html
 - title: About
   url: /about.html
 - title: Documentation
   url: /documentation.html

documentation:
 - title: USERS
   url: /user/overview/
 - title: ADMINS
   url: /admin/overview/
 - title: DEVELOPERS
   url: /developer/overview/

user-how-to:
 - title: Add a Doc URL to a Monitor
   url: add-a-doc-url-to-a-monitor.html
 - title: Add a Group to an Organization
   url: add-a-group-to-an-organization.html
 - title: Add a Variable
   url: add-a-variable.html
 - title: Add Cert to Compute to Enable SSL
   url: add-certs-to-compute-to-enable-ssl.html
 - title: Add CNAME in Azure DNS
   url: add-cname-to-azure-dns.html
 - title: Add CNAME
   url: add-cname.html
 - title: Add or Delete a Security Group to Open or Close an Additional Port
   url: add-or-delete-a-security-group-to-open-or-close-an-additional-port.html
 - title: Add or Edit Primary and Secondary Clouds
   url: add-edit-primary-secondary-clouds.html
 - title: Add a New Azure Cloud
   url: add-a-new-azure-cloud.html
 - title: Add a New Cloud
   url: add-a-new-cloud.html
 - title: Add a Platform Dependency
   url: add-a-platform-dependency.html
 - title: Add a Platform to a Design
   url: add-a-platform-to-a-design.html
 - title: Add or Reduce Capacity
   url: add-reduce-capacity.html
 - title: Add a Specific Component to a Design
   url: add-specific-component-to-a-design.html
 - title: Add a Team to an Assembly
   url: add-team-to-assembly.html
 - title: Add a User to a Team
   url: add-user-to-team.html
 - title: Add a User To a Group
   url: add-a-user-to-a-group.html
 - title: Add a User
   url: add-a-user.html
 - title: Assess the Health of Applications, Platforms and Clouds
   url: assess-health-applications-platforms-clouds.html
 - title: Auto Replace
   url: auto-replace.html
 - title: Auto Scale
   url: auto-scale.html
 - title: Bulk Actions
   url: bulk-actions.html
 - title: Catalogs
   url: catalogs.html
 - title: Check Status, Repair and Restart a VM
   url: check-status-repair-restart-vm.html
 - title: Configure App Version Monitor
   url: configure-app-version-monitor.html
 - title: Configure ECV Check URL on OneOps
   url: configure-ecv-check-url-on-oneops.html
 - title: Configure Tomcat HttpConnector Attributes in OneOps
   url: configure-tomcat-httpconnector-attributes-in-oneops.html
 - title: Control Environment
   url: control-environment.html
 - title: Create a Team in an Organization
   url: create-a-team-in-an-organization.html
 - title: Create Assemblies to Design Application
   url: create-assemblies-to-design-application.html
 - title: Create Environment Dependency with Environment Profiles
   url: create-environment-dependency-environment-profiles.html
 - title: Create an Environment
   url: create-an-environment.html
 - title: Delete an Environment
   url: delete-an-environment.html
 - title: Delete a Platform
   url: delete-platform.html
 - title: Deploy Application after Design Changes
   url: deploy-application-after-design-changes.html
 - title: Deploy an Application for the First Time
   url: deploy-application-for-first-time.html
 - title: Deploy an Environment
   url: deploy-environment.html
 - title: Deploy Multiple Clouds in Parallel
   url: deploy-multiple-clouds-in-parallel.html
 - title: Deploy an Organization
   url: deploy-an-organization.html
 - title: Deploy and Provision an Application and Environment for the First Time
   url: deploy-provision-application-environment-first-time.html
 - title: Deployment Approval Process
   url: deployment-approval-process.html
 - title: What compute sizes are available
   url: compute-sizes.html
 - title: Edit an Environment
   url: edit-environment.html
 - title: Edit a Platform
   url: edit-a-platform.html
 - title: Enable Access to an Assembly for a User on a Team
   url: enable-access-to-an-assembly-for-a-user-on-a-team.html
 - title: Enable https for a Service (LB Certs)
   url: enable-https-for-service-lbcerts.html
 - title: Enable Platform to Auto Replace Unhealthy Components
   url: enable-platform-auto-replace-unhealthy-components.html
 - title: Ensure that Alerts for Production Environment are Sent to NOC
   url: ensure-that-alerts-for-production-environment-are-sent-to-noc.html
 - title: Environment Releases
   url: environment-releases.html
 - title: Find the hostname of a VM
   url: find-hostname-of-vm.html
 - title: Find the IP Address for a Compute Node
   url: find-ip-address-for-compute-node.html
 - title: Find a Platform VIP Name
   url: find-platform-vip-name.html
 - title: Find VM IP Addresses
   url: find-vm-ip-addresses.html
 - title: Fix Unresponsive Compute
   url: fix-unresponsive-compute.html
 - title: Grep or Search Text in Files on Computes
   url: grep-or-search-text-in-files-on-computes.html
 - title: Import and Export Catalog
   url: import-and-export-catalog.html
 - title: Manage Assemblies
   url: manage-assemblies.html
 - title: Manage OneOps User Accounts
   url: manage-oneops-user-accounts.html
 - title: Open Files Monitor
   url: open-files-monitor.html
 - title: Operations Summary
   url: operations-summary.html
 - title: Organization Summary
   url: organization-summary.html
 - title: Reboot Computes
   url: reboot-computes.html
 - title: Remove an Unused Cloud from an Environment
   url: remove-unused-cloud-from-environment.html
 - title: Replace a Bad VM
   url: replace-a-bad-vm.html
 - title: Reports Summary
   url: reports-summary.html
 - title: Rollback Code
   url: rollback-code.html
 - title: Search Summary
   url: search-summary.html
 - title: Security Groups
   url: security-groups.html
 - title: Set Up a Custom Action
   url: set-up-a-custom-action.html
 - title: Set Up Notifications
   url: set-up-notifications.html
 - title: Set Up Your User Account
   url: set-up-your-user-account.html
 - title: Set Variable Cloud Scaling Percentage
   url: set-variable-cloud-scaling-percentage.html
 - title: Shutdown a Cloud
   url: shutdown-cloud.html
 - title: Specify an Email Address or Distribution List for Notifications
   url: specify-email-address-distribution-list-for-notifications.html
 - title: SSH to a Compute Node
   url: ssh-to-a-compute-node.html
 - title: SSH a VM
   url: ssh-vm.html
 - title: Start and Stop an Instance
   url: start-stop-instance.html
 - title: Take a Node out of Traffic (ECV Disable)
   url: take-node-out-of-traffic-ecv-disable.html
 - title: Update Oracle JDK/JRE Version on Java-based Platforms
   url: update-oracle-jdk-jre-version-java-based-platforms.html
 - title: Update OS Packages on a Compute
   url: update-os-packages-on-a-compute.html
 - title: Update the Size of a Compute
   url: update-size-of-compute.html
 - title: Update or Upgrade New OneOps Code
   url: update-upgrade-new-oneops-code.html
 - title: Upgrade an Application Version in an Environment
   url: upgrade-application-version-in-environment.html
 - title: Upgrade Specific OS Packages on a Compute
   url: upgrade-specific-os-package-on-compute.html
 - title: Variables Override Prevention
   url: avoid-override-variables.html
 - title: View a Reports Summary
   url: view-a-reports-summary.html
 - title: View, Add, or Edit Environment Profiles
   url: view-add-edit-environment-profiles.html
 - title: View an Organization Summary
   url: view-an-organization-summary.html
 - title: View Deployment Status
   url: view-deployment-status.html
 - title: View Design Releases
   url: view-design-releases.html
 - title: Watch a Notification
   url: watch-a-notification.html
                                         
         
sources:
 confluence:
  server: https://confluence.walmart.com
  pages: [PGPTOOLS/Test]

# ----------------------------------------------------------------------------------------------------------------------
# Theme
# ----------------------------------------------------------------------------------------------------------------------

bootstrapVersion: 3.3.1
#theme: walmart

# ----------------------------------------------------------------------------------------------------------------------
# Jekyll
# ----------------------------------------------------------------------------------------------------------------------
markdown: kramdown
kramddown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

exclude: [jekyll.jar, jekyll.sh, jekyll-stage.sh, jekyll-stage-serve.sh, jekyll-stage-build.sh, linkcheck.sh, linkcheck-results.log]
